---
- name: Enable Lmod on Master node
  replace:
    path: "/etc/sysconfig/modules/lmod/{{ item.path }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { path: 'cm-lmod-init.sh', regexp: 'LMOD=.*$', replace: 'LMOD=1'}
    - { path: 'cm-lmod-init.csh', regexp: 'LMOD.*$', replace: 'LMOD "1"'}

- name: Enable Lmod in image
  replace:
    path: "{{ cm_def_img_path }}/etc/sysconfig/modules/lmod/{{ item.path }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { path: 'cm-lmod-init.sh', regexp: 'LMOD=.*$', replace: 'LMOD=1'}
    - { path: 'cm-lmod-init.csh', regexp: 'LMOD.*$', replace: 'LMOD "1"'}

- name: Put DefaultModules in place
  template:
    src: DefaultModules.lua.j2
    dest: "{{ item }}"
  loop:
    - "/usr/share/modulefiles"
    - "{{ cm_def_img_path }}/usr/share/modulefiles"
