- name: Remove existing matlab app install
  file:
    path: /var/www/ood/apps/sys/matlab/
    state: absent

- name: matlab directory
  file:
    path: /var/www/ood/apps/sys/matlab
    state: directory

- name: Clone ood matlab app
  git:
    repo: "{{ matlab_ood_app_repo }}"
    dest: /var/www/ood/apps/sys/matlab/
    refspec: "{{ matlab_ood_app_refspec }}"
    version: "{{ matlab_ood_app_version }}"
