---
- name: Update SitePackge.lua
  copy:
    src: SitePackage.lua
    dest: "{{ lmod_loc }}/libexec/SitePackage.lua"

- name: Import file in warewulf
  import_tasks: warewulf_steps.yaml
  when: not cod_deploy

- name: Clone Lmod repo
  git:
    repo: "{{ lmod_repo }}"
    dest: /tmp/lmod
    refspec: "{{ lmod_refspec }}"
    version: "{{ lmod_version }}"

- name: Copy module tracking folder
  copy:
    src: /tmp/lmod/contrib/tracking_module_usage/
    dest: "{{ lmod_module_tracking_loc }}"
    remote_src: yes

- name: Remove lmod repo
  file:
    path: /tmp/lmod
    state: absent

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ lmod_archive_loc }}"
    - "{{ lmod_log_loc }}"
    - "{{ lmod_share_loc }}"

- name: Update rsyslog.d
  lineinfile:
    path: /etc/rsyslog.conf
    line: '\$IncludeConfig /etc/rsyslog.d/\*.conf)'
    backup: yes

- name: Put rsyslog config file in place
  template:
    src: rsyslog.j2
    dest: /etc/rsyslog.d/moduleTracking.conf

- name: Set up log rotate for module usage
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/moduleUsage

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
