---
- name: Get node list
  command: "wwsh node list -1"
  ignore_errors: yes
  register: node_list

- name: Add SitePackage.lua to warewulf database
  command: "wwsh file import {{ lmod_loc }}/libexec/SitePackage.lua"

- name: Add file for provision
  command: "wwsh -y provision set {{ item }} --fileadd=SitePackage.lua"
  loop: "{{ node_list.stdout_lines | map('trim') | list }}"

