---
- hosts: headnode
  roles:
    - { name: 'pre_ohpc', tags: 'pre_ohpc' }
    - { name: 'ohpc_install', tags: 'ohpc_install' }
    - { name: 'ohpc_config', tags: 'ohpc_config' }
    - { name: 'lmod_db', tags: 'lmod_db' }
    - { name: 'compute_build_vnfs', tags: 'compute_build_vnfs' }
    - { name: 'compute_build_nodes', tags: 'compute_build_nodes' }
    - { name: 'nodes_vivify', tags: 'nodes_vivify' }
    - { name: 'ohpc_add_easybuild', tags: 'ohpc_add_easybuild' }
    - { name: 'ohpc_jupyter', tags: 'ohpc_jupyter', when: jupyter_provision}
    - { name: 'ohpc_matlab', tags: 'ohpc_matlab', when: matlab_provision }
    - { name: 'ohpc_sas', tags: 'ohpc_sas', when: sas_provision }
    - { name: 'ohpc_igv', tags: 'ohpc_igv', when: igv_provision }
    - { name: 'ohpc_ansys', tags: 'ohpc_ansys', when: ansys_provision }
    - { name: 'ohpc_add_rstudio', tags: 'ohpc_add_rstudio', when: rstudio_provision }
    - { name: 'ohpc_user_reg', tags: 'ohpc_user_reg', when: enable_user_reg }
