---
- hosts: chroot
  roles:
    - { name: 'ood', tags: 'ood' }
    - { name: 'ood_fix_cache', tags: 'ood_fix_cache' }
    - { name: 'ood_enable_ssl', tags: 'ood_enable_ssl' }
    - { name: 'ood_jupyter', tags: 'ood_jupyter', when: jupyter_provision}
    - { name: 'ood_jupyterlab', tags: 'ood_jupyterlab', when: jupyterlab_provision }
    - { name: 'ood_vnc_form', tags: 'ood_vnc_form' }
    - { name: 'ood_add_rstudio', tags: 'ood_add_rstudio', when: rstudio_provision }
    - { name: 'ood_matlab', tags: 'ood_matlab', when: matlab_provision }
    - { name: 'ood_sas', tags: 'ood_sas', when: sas_provision }
    - { name: 'ood_firewall_and_services', tags: 'ood_firewall_and_services' }
    - { name: 'ohpc_firewall_and_services', tags: 'ohpc_firewall_and_services' }
    - { name: 'ood_shib_install', tags: 'ood_shib_install', when: install_shib }
    - { name: 'ood_shib_config', tags: 'ood_shib_config', when: configure_shib }
    - { name: 'ood_user_reg_ops', tags: 'ood_user_reg_ops' }
    - { name: 'ood_user_reg_cloud', tags: 'ood_user_reg_cloud' }
