---
- hosts: ood
  become: true
  roles:
    - { name: 'ood', tags: 'ood' }
    - { name: 'ood_fix_cache', tags: 'ood_fix_cache' }
    - { name: 'ood_shib_install', tags: 'ood_shib_install', when: install_shib }
    - { name: 'ood_shib_config', tags: 'ood_shib_config', when: configure_shib }
    - { name: 'ood_enable_ssl', tags: 'ood_enable_ssl' }
    - { name: 'enable_lmod', tags: 'enable_lmod' }
    - { name: 'ood_user_reg_ops', tags: 'ood_user_reg_cloud' }
    - { name: 'ood_user_reg_cloud', tags: 'ood_user_reg_cloud' }
    - { name: 'ood_vnc_form', tags: 'ood_vnc_form' }
    - { name: 'ood_jupyter', tags: 'ood_jupyter', when: jupyter_provision}
    - { name: 'ood_rstudio', tags: 'ood_rstudio', when: rstudio_provision }
    - { name: 'ood_matlab', tags: 'ood_matlab', when: matlab_provision }
    - { name: 'ood_sas', tags: 'ood_sas', when: sas_provision }
    - { name: 'ood_ansys', tags: 'ood_ansys', when: ansys_provision }
    - { name: 'ood_igv', tags: 'ood_igv', when: igv_provision }
