---
title: "HPC Desktop"
cluster: {{ cluster_name }} 
submit: "submit/submit.yml.erb"
attributes:
  desktop: "xfce"
  bc_num_slots:
    label: Number of CPU
    value: 1
    min: 1
    max: 24
    step: 1

  bc_num_mems:
    widget: "number_field"
    label: Memory per CPU (GB)
    value: 4
    min: 1
    max: 128
    step: 1

  bc_partition:
    widget: select
    label: Partition
    options:
      - [ "defq", "defq" ]
      - [ "low", "low" ]

form:
  - desktop
  - bc_num_hours
  - bc_partition
  - bc_num_slots
  - bc_num_mems
  - bc_email_on_started
