- name: Remove existing igv app install
  file:
    path: "{{ igv_ood_app_dir }}"
    state: absent

- name: igv directory
  file:
    path: "{{ igv_ood_app_dir }}"
    state: directory

- git:
    repo: "{{ igv_ood_repo }}"
    dest: "{{ igv_ood_app_dir }}"
    clone: yes
    version: "{{ igv_ood_app_version }}" 
