---
v2:
  metadata:
    title: "{{ cluster_title }}"
  login:
    host: "{{ cluster_host }}"
    default: true
  job:
    adapter: "slurm"
    bin: "{{ slurm_bin_path }}"
    conf: "{{ slurm_conf_path }}"
  batch_connect:
    basic:
      script_wrapper: |
        module reset
        %s
      set_host: "host=$(hostname -s)"
    vnc:
      script_wrapper: |
        module reset
        export PATH="/opt/TurboVNC/bin:$PATH"
        export WEBSOCKIFY_CMD="/bin/websockify"
        %s
      set_host: "host=$(hostname -s)"

