- name: enable ssl
  blockinfile:
    path: /etc/ood/config/ood_portal.yml
    insertbefore: "#ssl:"
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK ssl"
    block: |
      ssl:
        - 'SSLCertificateFile "/etc/pki/tls/certs/localhost.crt"'
        - 'SSLCertificateKeyFile "/etc/pki/tls/private/localhost.key"'

- name: Build the updated Apache config
  command: /opt/ood/ood-portal-generator/sbin/update_ood_portal
  ignore_errors: yes 

- name: Restart service httpd24, in all cases
  service:
    name: httpd24-httpd
    state: restarted
