---
- name: Remove existing jupyter app install
  file:
    path: /var/www/ood/apps/sys/jupyter/
    state: absent

- name: Creates directory to clone the jupyter app
  file:
    path: /var/www/ood/apps/sys/jupyter/
    state: directory

- name: Clone the default jupyter app from OOD
  git:
    repo: "{{ jupyter_ood_app_repo }}"
    dest: /var/www/ood/apps/sys/jupyter
    refspec: "{{ jupyter_ood_app_refspec }}"
    version: "{{ jupyter_ood_app_version }}"
