---
- name: Remove existing jupyter app install
  file:
    path: /var/www/ood/apps/sys/jupyter/
    state: absent

- name: Creates directory to clone the jupyter app
  file:
    path: /var/www/ood/apps/sys/jupyter/
    state: directory

- name: Clone the default jupyter app from OOD
  git:
    repo: "{{ jupyter_ood_app_repo }}"
    dest: /var/www/ood/apps/sys/jupyter
    refspec: "{{ jupyter_ood_app_refspec }}"
    version: "{{ jupyter_ood_app_version }}"

- name: Use custom form.yml from templates for jupyter app 
  template:
    src: custom-jupyter-form.yml
    dest: /var/www/ood/apps/sys/jupyter/form.yml

- name: Use submit.yml.erb file tailored for slurm usage at UAB
  copy:
    src: jupyter-submit.yml.erb
    dest: /var/www/ood/apps/sys/jupyter/submit.yml.erb

- name: Use custom script.sh.erb provided to avoid Jupyter Crash with user id!=1000
  template:
    src: jupyter-script.sh.erb
    dest: /var/www/ood/apps/sys/jupyter/template/script.sh.erb
