---
- name: install warewulf file synchronization
  copy:
    src: warewulf
    dest: /
    owner: root
    group: root

# ensure script files are executable
- file:
    path: /warewulf/bin
    recurse: true
    mode: u+x,g+x

- name: create custom warewulf config file for node
  template:
    src: wwnodeconf.j2
    dest: /warewulf/config
    owner: root
    group: root
    mode: 0640

- name: add warewulf file sync via cron
  copy:
    src: wwupdatefiles
    dest: /etc/cron.d
    owner: root
    group: root
    mode: 0640

- name: create log output dir for warewulf cron
  file:
    path: /var/log/warewulf
    state: directory
    owner: root
    group: root
    mode: 755
