---

   - name: start munge
     service: name=munge state=restarted enabled=yes

   - name: start slurmctld
     service: name=slurmctld state=restarted enabled=yes

   - name: Waiting for slurmd to enable on the compute nodes after restart
     pause:
       seconds: 30
