---

   - name: start munge
     service: name=munge state=restarted enabled=yes

   - name: start slurmctld
     service: name=slurmctld state=restarted enabled=yes

   - name: Waiting for slurmd to enable on the compute nodes after restart
     pause:
       seconds: 30

   - name: update slurm status on nodes
     shell: scontrol update nodename=$(wwsh node list | tail --lines=+3 | cut -f 1 -d' '| tr '\n' ',') state=IDLE

   - name: update pxeconfig to let node boot locally
     shell: wwsh -y object modify -s bootlocal=EXIT -t node $(wwsh node list | tail --lines=+3 | cut -f 1 -d' '| tr '\n' ' ') 
     when: stateful_nodes == true
