---
- name: Remove existing ANSYS app install
  file:
    path: "{{ ansys_ood_app_dir }}"
    state: absent

- name: Create ANSYS app directory
  file:
    path: "{{ ansys_ood_app_dir }}"
    state: directory

- git:
    repo: "{{ ansys_ood_repo }}"
    dest: "{{ ansys_ood_app_dir }}"
    clone: yes
    version: "{{ ansys_ood_app_version }}" 
