- name: Remove existing SAS app install
  file:
    path: /var/www/ood/apps/sys/sas/
    state: absent

- name: Create SAS app directory
  file:
    path: /var/www/ood/apps/sys/sas
    state: directory

- name: Clone ood sas template
  git:
    repo: "{{ sas_ood_app_repo }}"
    dest: /var/www/ood/apps/sys/sas/
    refspec: "{{ sas_ood_app_refspec }}"
    version: "{{ sas_ood_app_version }}"
