---
- name: Download checksum file
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ ver }}/{{ sha256 }}"
    dest: "/tmp/{{ sha256 }}"

- set_fact:
    md5_value: "{{ lookup('file', '/tmp/{{ sha256 }}') }}"

- name: Download node_exporter binary
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ ver }}/{{ file }}"
    dest: "/tmp/{{ file }}"
    checksum: "sha256:{{ md5_value }}"
    force: true

- name: Extract node_exporter
  unarchive:
    src: "/tmp/{{ file }}"
    dest: "/tmp"
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Add system user
  user:
    name: node_exporter
    shell: /bin/false
    system: yes

- name: Copy node_exporter binary
  copy:
    src: "{{ scriptdir }}/tmp/{{ file | regex_replace('.tar.gz', '') }}/node_exporter"
    dest: /usr/local/bin/node_exporter
    owner: root
    group: root
    mode: 0755

- name: Copy systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Reload systemd daemons
  systemd:
    daemon_reload: yes
    
- name: Restart node_exporter service
  systemd:
    name: node_exporter
    state: restarted
    enabled: true