- name: Add shibboleth openSUSE build service repository
  yum_repository:
    name: shibboleth
    description: Shibboleth (CentOS_7)
    mirrorlist: https://shibboleth.net/cgi-bin/mirrorlist.cgi/CentOS_7
    gpgkey: https://shibboleth.net/downloads/service-provider/RPMS/repomd.xml.key
    gpgcheck: no
    enabled: yes

# note the copr repo for shibboleth was added during node prep roles
- name: install shibboleth rpm for scl apache
  yum: name=shibboleth state=latest

# note the shibboleth rpm is not fully scl-yet so need hand correction
- name: copy shibbolth apache module into ood scl installe
  copy:
    src: /etc/httpd/conf.d/shib.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/
    remote_src: yes
