---
cluster: "{{ cluster_name }}"
attributes:
  bc_num_hours:
    value: 1

  bc_num_slots:
    label: Number of CPU
    value: 1
    min: 1
    max: 24
    step: 1

  bc_num_mems:
    widget: "number_field"
    label: Memory per CPU (GB)
    value: 4
    min: 1
    max: 128
    step: 1

  bc_partition:
    widget: select
    label: Partition
    options:
      - [ "low", "low" ]

  version:
    widget: select
    label: "SAS version"
    help: "This defines the version of SAS you want to load."
    options:
      - [ "v9.4", "sas/v9.4" ]
form:
  - version
  - bc_num_hours
  - bc_partition
  - bc_num_slots
  - bc_num_mems
  - bc_email_on_started
